name: Build and Test UCrypt Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Job 1: Build the Java backend JAR file
  build-backend:
    runs-on: ubuntu-latest
    outputs:
      jar_name: ${{ steps.get_jar_name.outputs.JAR_NAME }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build backend with Maven
        run: mvn -B package --file crypto-back/pom.xml -DskipTests

      - name: Get Jar file name
        id: get_jar_name
        run: echo "JAR_NAME=$(ls crypto-back/target/*.jar)" >> $GITHUB_OUTPUT

      - name: Upload backend artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-jar
          path: ${{ steps.get_jar_name.outputs.JAR_NAME }}

  # Job 2: Build the Angular frontend static files
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Frontend Dependencies and Build
        run: |
          cd UCryptPortal
          npm install
          npm install -g @angular/cli@15.0.1
          ng build --configuration=docker

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-dist
          path: UCryptPortal/dist/

  # Job 3: Run the automated Selenium tests
  run-automated-tests:
    runs-on: ubuntu-latest
    # This job depends on the backend and frontend builds finishing successfully
    needs: [build-backend, build-frontend]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download backend artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-jar
          path: crypto-back/target/

      - name: Download frontend artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend-dist
          path: UCryptPortal/dist/

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Start services with Docker Compose
        run: docker-compose -f crypto-back/docker-compose-ci.yml up -d

      - name: Wait for services to be healthy
        run: |
          echo "Waiting for services to be ready..."
          # This is a simple delay. A more robust solution would be to poll the health checks.
          sleep 60 

      - name: Run Selenium tests
        run: mvn -B test -f testing/pom.xml

      - name: Publish Test Report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always() # This ensures the report is published even if tests fail
        with:
          files: '**/surefire-reports/TEST-*.xml'